export type ImageGenerationClientOptions = {
  apiKey?: string;
  baseUrl?: string;
  model?: string;
  size?: string;
  quality?: string;
  timeoutMs?: number;
};

export type GeneratedImage = {
  buffer: Buffer;
  contentType: 'image/png' | 'image/jpeg' | 'image/webp';
  model: string;
};

/**
 * Minimal OpenAI Images API client. Generated bytes are downloaded/decoded
 * immediately so callers can persist them instead of depending on temporary
 * provider URLs.
 */
export class ImageGenerationClient {
  private readonly apiKey: string | undefined;
  private readonly baseUrl: string;
  private readonly model: string;
  private readonly size: string;
  private readonly quality: string;
  private readonly timeoutMs: number;

  constructor(options: ImageGenerationClientOptions = {}) {
    this.apiKey = options.apiKey;
    this.baseUrl = (options.baseUrl ?? 'https://api.openai.com/v1').replace(
      /\/$/,
      '',
    );
    this.model = options.model ?? 'gpt-image-1';
    this.size = options.size ?? '1024x1024';
    this.quality = options.quality ?? 'medium';
    this.timeoutMs = options.timeoutMs ?? 120_000;
  }

  isConfigured(): boolean {
    return Boolean(this.apiKey?.trim());
  }

  getModel(): string {
    return this.model;
  }

  async generate(prompt: string): Promise<GeneratedImage> {
    if (!this.isConfigured()) {
      throw new Error('Image generation is not configured (missing API key)');
    }

    const signal = AbortSignal.timeout(this.timeoutMs);
    const response = await fetch(`${this.baseUrl}/images/generations`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${this.apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: this.model,
        prompt,
        n: 1,
        size: this.size,
        quality: this.quality,
        output_format: 'webp',
      }),
      signal,
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(
        `Image generation HTTP ${response.status}: ${text.slice(0, 500)}`,
      );
    }

    const body = (await response.json()) as {
      data?: Array<{ b64_json?: string; url?: string }>;
    };
    const image = body.data?.[0];
    if (!image) {
      throw new Error('Image generation returned no image');
    }

    if (image.b64_json) {
      const buffer = Buffer.from(image.b64_json, 'base64');
      if (buffer.length === 0) {
        throw new Error('Image generation returned empty image data');
      }
      return {
        buffer,
        contentType: this.detectContentType(buffer, 'image/webp'),
        model: this.model,
      };
    }

    if (image.url) {
      return this.downloadGeneratedUrl(image.url, signal);
    }

    throw new Error('Image generation response contained no image bytes or URL');
  }

  private async downloadGeneratedUrl(
    url: string,
    signal: AbortSignal,
  ): Promise<GeneratedImage> {
    const response = await fetch(url, { signal });
    if (!response.ok) {
      throw new Error(`Generated image download HTTP ${response.status}`);
    }

    const buffer = Buffer.from(await response.arrayBuffer());
    if (buffer.length === 0) {
      throw new Error('Generated image download returned empty data');
    }
    const rawType = response.headers.get('content-type')?.split(';')[0]?.trim();
    const contentType = this.detectContentType(
      buffer,
      this.asSupportedContentType(rawType),
    );
    return { buffer, contentType, model: this.model };
  }

  private asSupportedContentType(
    value: string | undefined,
  ): GeneratedImage['contentType'] {
    if (
      value === 'image/png' ||
      value === 'image/jpeg' ||
      value === 'image/webp'
    ) {
      return value;
    }
    return 'image/webp';
  }

  private detectContentType(
    buffer: Buffer,
    fallback: GeneratedImage['contentType'],
  ): GeneratedImage['contentType'] {
    if (
      buffer.length >= 12 &&
      buffer.subarray(0, 4).toString('ascii') === 'RIFF' &&
      buffer.subarray(8, 12).toString('ascii') === 'WEBP'
    ) {
      return 'image/webp';
    }
    if (
      buffer.length >= 8 &&
      buffer.subarray(0, 8).equals(
        Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
      )
    ) {
      return 'image/png';
    }
    if (buffer.length >= 3 && buffer[0] === 0xff && buffer[1] === 0xd8) {
      return 'image/jpeg';
    }
    return fallback;
  }
}
